apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.tenant.name }}
  namespace: deployaz-{{ .Values.tenant.name }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.tenant.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.tenant.name }}
                port:
                  number: 80
