apiVersion: v1
kind: LimitRange
metadata:
  name: tenant-limits
  namespace: deployaz-{{ .Values.tenant.name }}
spec:
  limits:
    - type: Container
      default:
        cpu: {{ .Values.resources.limits.cpu }}
        memory: {{ .Values.resources.limits.memory }}
      defaultRequest:
        cpu: {{ .Values.resources.requests.cpu }}
        memory: {{ .Values.resources.requests.memory }}
