apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tenant.name }}
  namespace: deployaz-{{ .Values.tenant.name }}
  labels:
    app: {{ .Values.tenant.name }}
spec:
  selector:
    app: {{ .Values.tenant.name }}
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.tenant.port | int }}
{{- if .Values.tenant.metrics.enabled }}
    - name: management
      port: {{ .Values.tenant.metrics.port | int }}
      targetPort: {{ .Values.tenant.metrics.port | int }}
{{- end }}
