apiVersion: v1
kind: ServiceAccount
metadata:
  name: tenant-b-sa
  namespace: deployaz-tenant-b
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tenant-b-namespace-admin
  namespace: deployaz-tenant-b
rules:
  - apiGroups: ["", "apps"]
    resources: ["pods", "services", "deployments", "configmaps", "secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tenant-b-namespace-admin-binding
  namespace: deployaz-tenant-b
subjects:
  - kind: ServiceAccount
    name: tenant-b-sa
    namespace: deployaz-tenant-b
roleRef:
  kind: Role
  name: tenant-b-namespace-admin
  apiGroup: rbac.authorization.k8s.io
